create table author (birth_date date, death_date date, work_count integer not null, id bigint not null auto_increment, author_key varchar(255), name varchar(255), top_work varchar(255), primary key (id)) engine=InnoDB;
create table author_alternate_names (author_id bigint not null, alternate_name varchar(255)) engine=InnoDB;
create table author_top_subjects (author_id bigint not null, top_subject varchar(255)) engine=InnoDB;
create table book (id bigint not null auto_increment, book_key varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table book_authors (author_id bigint not null, book_id bigint not null) engine=InnoDB;
create table book_subjects (book_id bigint not null, subject_id bigint not null) engine=InnoDB;
create table counts (five_stars integer, four_stars integer, one_star integer, three_stars integer, two_stars integer, id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table edition (first_publish_date date, book_id bigint, id bigint not null auto_increment, edition_key varchar(255), language varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table edition_covers (cover_id integer, edition_id bigint not null) engine=InnoDB;
create table edition_subject_people (edition_id bigint not null, subject_person varchar(255)) engine=InnoDB;
create table edition_subject_places (edition_id bigint not null, subject_place varchar(255)) engine=InnoDB;
create table edition_subject_times (edition_id bigint not null, subject_time varchar(255)) engine=InnoDB;
create table edition_subjects (edition_id bigint not null, subject varchar(255)) engine=InnoDB;
create table rating (book_id bigint, counts_id bigint, id bigint not null auto_increment, summary_id bigint, primary key (id)) engine=InnoDB;
create table review (rating integer not null, review_date date, book_id bigint, id bigint not null auto_increment, user_id bigint, content varchar(255), primary key (id)) engine=InnoDB;
create table subject (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table summary (average float(53) not null, count integer not null, sortable_average float(53), id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email varchar(255), password varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table rating add constraint UKn9erjeygxsfdckvk5xn2rana2 unique (book_id);
alter table rating add constraint UK3i57xx80k4jcdsfyjw1klpowf unique (counts_id);
alter table rating add constraint UKs0ydtoxs1mgre7deky7dr57jq unique (summary_id);
alter table author_alternate_names add constraint FK6kobtojlvpsv1g3iylaxedg4r foreign key (author_id) references author (id);
alter table author_top_subjects add constraint FKi6a38a80b0kdfdthyol9nv0hi foreign key (author_id) references author (id);
alter table book_authors add constraint FK78gu95lglhc6cs2u5jfudx6e5 foreign key (author_id) references author (id);
alter table book_authors add constraint FKs4xm7q8i3uxvaiswj1c35nnxw foreign key (book_id) references book (id);
alter table book_subjects add constraint FK5e5e2mm5nwpq5sa22aymi4kue foreign key (subject_id) references subject (id);
alter table book_subjects add constraint FK3v0mulxwj5chak3egd825lvqb foreign key (book_id) references book (id);
alter table edition add constraint FK7q57m1a7u3voirj9k9ncugsdr foreign key (book_id) references book (id);
alter table edition_covers add constraint FK6o2dljxpi484r75n4p4j3oqa0 foreign key (edition_id) references edition (id);
alter table edition_subject_people add constraint FKeuo5q3asus7lkh49079p1ue3h foreign key (edition_id) references edition (id);
alter table edition_subject_places add constraint FKewyvsu4y6lf9ypphrbuih8odt foreign key (edition_id) references edition (id);
alter table edition_subject_times add constraint FKb87xfa0pxq4mon3d0881eqiun foreign key (edition_id) references edition (id);
alter table edition_subjects add constraint FKcvpl8qhbvyrdgm7necersifxt foreign key (edition_id) references edition (id);
alter table rating add constraint FK7y1acs6la7vkgb5ulm44729sc foreign key (book_id) references book (id);
alter table rating add constraint FK7vdfj1ws1vi3fruh4cxorapiy foreign key (counts_id) references counts (id);
alter table rating add constraint FKsoec5tjdl6a14aahd17upf9v foreign key (summary_id) references summary (id);
alter table review add constraint FK70yrt09r4r54tcgkrwbeqenbs foreign key (book_id) references book (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
