alter table author_alternate_names drop foreign key FK6kobtojlvpsv1g3iylaxedg4r;
alter table author_top_subjects drop foreign key FKi6a38a80b0kdfdthyol9nv0hi;
alter table book_authors drop foreign key FK78gu95lglhc6cs2u5jfudx6e5;
alter table book_authors drop foreign key FKs4xm7q8i3uxvaiswj1c35nnxw;
alter table book_subjects drop foreign key FK5e5e2mm5nwpq5sa22aymi4kue;
alter table book_subjects drop foreign key FK3v0mulxwj5chak3egd825lvqb;
alter table edition drop foreign key FK7q57m1a7u3voirj9k9ncugsdr;
alter table edition_covers drop foreign key FK6o2dljxpi484r75n4p4j3oqa0;
alter table edition_subject_people drop foreign key FKeuo5q3asus7lkh49079p1ue3h;
alter table edition_subject_places drop foreign key FKewyvsu4y6lf9ypphrbuih8odt;
alter table edition_subject_times drop foreign key FKb87xfa0pxq4mon3d0881eqiun;
alter table edition_subjects drop foreign key FKcvpl8qhbvyrdgm7necersifxt;
alter table rating drop foreign key FK7y1acs6la7vkgb5ulm44729sc;
alter table rating drop foreign key FK7vdfj1ws1vi3fruh4cxorapiy;
alter table rating drop foreign key FKsoec5tjdl6a14aahd17upf9v;
alter table review drop foreign key FK70yrt09r4r54tcgkrwbeqenbs;
alter table review drop foreign key FKiyf57dy48lyiftdrf7y87rnxi;
drop table if exists author;
drop table if exists author_alternate_names;
drop table if exists author_top_subjects;
drop table if exists book;
drop table if exists book_authors;
drop table if exists book_subjects;
drop table if exists counts;
drop table if exists edition;
drop table if exists edition_covers;
drop table if exists edition_subject_people;
drop table if exists edition_subject_places;
drop table if exists edition_subject_times;
drop table if exists edition_subjects;
drop table if exists rating;
drop table if exists review;
drop table if exists subject;
drop table if exists summaryDto;
drop table if exists user;
